# PARAMETERS TO CONTROL THE BEHAVIOR OF THE GAME ENGINE
# DO NOT REMOVE OR RENAME THIS FILE
PLAYER_1_NAME = "rishabh_bot"
PLAYER_1_PATH = "./rishabh_bot"
PLAYER_2_NAME = "check_call_bot"
PLAYER_2_PATH = "./check_call_bot"
GAME_LOG_FILENAME = "gamelog"
RESULTS_DIR = "./statistics/tmp"
PLAYER_LOG_SIZE_LIMIT = 524288
ENFORCE_GAME_CLOCK = True
STARTING_GAME_CLOCK = 180.0
BUILD_TIMEOUT = 10.0
CONNECT_TIMEOUT = 10.0
NUM_ROUNDS = 1000
STARTING_STACK = 250
BIG_BLIND = 5
SMALL_BLIND = 2
PLAYER_TIMEOUT = 180
