'''
Build4Good 2026 PokerBot — Monte Carlo + Redraw Lookup Strategy

Rules:
  - 1000 hands/match, 250 chips/hand, blinds 2 (SB) / 5 (BB)
  - Streets: 0=preflop, 3=flop, 4=turn, 5=river
  - WE can redraw once per hand (street < 5); OPPONENT CANNOT redraw
  - RedrawAction(target_type, target_index, betting_action)
    target_type : 'hole' (index 0-1) or 'board' (index 0-2 flop, 0-3 turn)
  - 180s total time limit per match

Strategy:
  Preflop  — lookup table (n=100k MC) gives base equity + redraw gain per hand.
             Redraw the weaker hole card when equity is weak and gain is large.
             With 250 chips and 5BB, stack-to-blind ratio is only 50x — play tighter.
  Postflop — fast on-the-fly MC (~150-300 iters). Evaluate best redraw target
             (hole or board). Use redraw when it provides meaningful equity gain.
  Sizing   — with shallow stacks (250 chips, 5BB), pot grows fast. Bet 1/2-pot
             with strong hands, push all-in with very strong hands.
'''

import os
import random
import pickle
from collections import Counter

from skeleton.actions import FoldAction, CallAction, CheckAction, RaiseAction, RedrawAction
from skeleton.states import STARTING_STACK, BIG_BLIND
from skeleton.bot import Bot
from skeleton.runner import parse_args, run_bot

# ---------------------------------------------------------------------------
# Game constants (2026 updated rules)
# ---------------------------------------------------------------------------

STARTING_STACK = 250
BIG_BLIND      = 5
SMALL_BLIND    = 2

RANKS = '23456789TJQKA'
SUITS = 'cdhs'
DECK  = [r + s for r in RANKS for s in SUITS]

# Lookup table generated by generate_lookup.py (lives one dir up)
_HERE       = os.path.dirname(os.path.abspath(__file__))
LOOKUP_PATH = os.path.join(_HERE, '..', 'preflop_lookup.pkl')

# ---------------------------------------------------------------------------
# Redraw thresholds
# Since opponent cannot redraw, our redraw is a pure asymmetric edge.
# Be more aggressive about using it — lower the gain threshold.
# ---------------------------------------------------------------------------
PREFLOP_REDRAW_EQ_MAX   = 0.44   # redraw preflop if equity below this
PREFLOP_REDRAW_MIN_GAIN = 0.03   # and gain >= this (lower bar since opponent can't redraw)
POST_REDRAW_EQ_MAX      = 0.40
POST_REDRAW_MIN_GAIN    = 0.04

# ---------------------------------------------------------------------------
# Betting thresholds
# With 50x stack-to-blind, play tighter preflop. Shallower stacks mean
# pot odds shift quickly — be more willing to commit with strong hands.
# ---------------------------------------------------------------------------
RAISE_STRONG   = 0.62
RAISE_MODERATE = 0.52
CALL_MIN       = 0.38
BLUFF_MAX      = 0.20

# Preflop fold threshold — with 5BB, don't call raises with garbage
PREFLOP_FOLD_EQ = 0.36


# ---------------------------------------------------------------------------
# Preflop lookup table
# ---------------------------------------------------------------------------

def _load_lookup():
    try:
        with open(LOOKUP_PATH, 'rb') as f:
            return pickle.load(f)
    except FileNotFoundError:
        return {}

LOOKUP = _load_lookup()


def hand_to_key(cards):
    r0, s0 = cards[0][0], cards[0][1]
    r1, s1 = cards[1][0], cards[1][1]
    i0, i1 = RANKS.index(r0), RANKS.index(r1)
    if i0 < i1:
        r0, s0, i0, r1, s1, i1 = r1, s1, i1, r0, s0, i0
    if i0 == i1:
        return f"{r0}{r1}"
    return f"{r0}{r1}s" if s0 == s1 else f"{r0}{r1}o"


# ---------------------------------------------------------------------------
# Hand evaluator
# ---------------------------------------------------------------------------

def _parse(card):
    return (RANKS.index(card[0]), SUITS.index(card[1]))


def _hand_rank(cards):
    ranks = [c[0] for c in cards]
    suits = [c[1] for c in cards]

    flush_suit = next((s for s in range(4) if suits.count(s) >= 5), None)
    fc = [c for c in cards if c[1] == flush_suit] if flush_suit is not None else []

    def best_str(rs):
        rs = sorted(rs)
        if 12 in rs:
            rs = [-1] + rs
        best = -1
        for i in range(len(rs) - 4):
            w = rs[i:i+5]
            if w[-1] - w[0] == 4 and len(set(w)) == 5:
                best = max(best, w[-1])
        return best

    if fc:
        sf = best_str({c[0] for c in fc})
        if sf >= 0:
            return (8, sf)

    cnt    = Counter(ranks)
    groups = sorted(cnt.items(), key=lambda x: (x[1], x[0]), reverse=True)
    counts = [g[1] for g in groups]
    ordered = []
    for r, c in groups:
        ordered.extend([r] * c)

    if counts[0] == 4:                   return (7, ordered)
    if counts[0] == 3 and counts[1] >= 2: return (6, ordered)
    if fc:                               return (5, sorted([c[0] for c in fc], reverse=True)[:5])
    sh = best_str(set(ranks))
    if sh >= 0:                          return (4, [sh])
    if counts[0] == 3:                   return (3, ordered)
    if counts[0] == 2 and counts[1] == 2: return (2, ordered)
    if counts[0] == 2:                   return (1, ordered)
    return (0, sorted(ranks, reverse=True))


_7C5 = [
    (0,1,2,3,4),(0,1,2,3,5),(0,1,2,3,6),(0,1,2,4,5),(0,1,2,4,6),
    (0,1,2,5,6),(0,1,3,4,5),(0,1,3,4,6),(0,1,3,5,6),(0,1,4,5,6),
    (0,2,3,4,5),(0,2,3,4,6),(0,2,3,5,6),(0,2,4,5,6),(0,3,4,5,6),
    (1,2,3,4,5),(1,2,3,4,6),(1,2,3,5,6),(1,2,4,5,6),(1,3,4,5,6),
    (2,3,4,5,6),
]


def best_hand(hole_cards, board_cards):
    all_cards = [c for c in hole_cards + board_cards if c and c != '??']
    parsed    = [_parse(c) for c in all_cards]
    n         = len(parsed)
    if n < 5:
        return (-1,)
    best = (-1,)
    combos = _7C5 if n == 7 else [tuple(range(n))]
    for idx in combos:
        if max(idx) < n:
            score = _hand_rank([parsed[i] for i in idx])
            if score > best:
                best = score
    return best


# ---------------------------------------------------------------------------
# Monte Carlo equity
# ---------------------------------------------------------------------------

def _known(hole_cards, board_cards):
    return {c for c in hole_cards + board_cards if c and c != '??'}


def mc_equity(hole_cards, board_cards, n=200):
    known        = _known(hole_cards, board_cards)
    remaining    = [c for c in DECK if c not in known]
    board_needed = 5 - len(board_cards)
    wins = 0.0
    for _ in range(n):
        s          = random.sample(remaining, board_needed + 2)
        full_board = board_cards + s[2:]
        my  = best_hand(hole_cards, full_board)
        opp = best_hand(s[:2],      full_board)
        if   my > opp: wins += 1.0
        elif my == opp: wins += 0.5
    return wins / n


def mc_redraw_hole(hole_cards, board_cards, idx, n=120):
    base_rem  = [c for c in DECK if c not in _known(hole_cards, board_cards)]
    bn        = 5 - len(board_cards)
    wins = 0.0; count = 0
    for _ in range(n):
        if len(base_rem) < 1 + bn + 2: break
        s         = random.sample(base_rem, 1 + bn + 2)
        new_hole  = list(hole_cards); new_hole[idx] = s[0]
        fb        = board_cards + s[1:1+bn]
        my  = best_hand(new_hole, fb)
        opp = best_hand(s[1+bn:], fb)
        if   my > opp: wins += 1.0
        elif my == opp: wins += 0.5
        count += 1
    return wins / count if count else 0.0


def mc_redraw_board(hole_cards, board_cards, bidx, n=120):
    base_rem = [c for c in DECK if c not in _known(hole_cards, board_cards)]
    bn       = 5 - len(board_cards)
    wins = 0.0; count = 0
    for _ in range(n):
        if len(base_rem) < 1 + bn + 2: break
        s         = random.sample(base_rem, 1 + bn + 2)
        new_board = list(board_cards); new_board[bidx] = s[0]
        fb        = new_board + s[1:1+bn]
        my  = best_hand(hole_cards, fb)
        opp = best_hand(s[1+bn:],   fb)
        if   my > opp: wins += 1.0
        elif my == opp: wins += 0.5
        count += 1
    return wins / count if count else 0.0


def best_redraw(hole_cards, board_cards, n=100):
    """Return (equity, target_type, target_index) for the best redraw option."""
    best = (-1.0, 'hole', 0)
    for i in range(len(hole_cards)):
        if not hole_cards[i] or hole_cards[i] == '??': continue
        eq = mc_redraw_hole(hole_cards, board_cards, i, n)
        if eq > best[0]: best = (eq, 'hole', i)
    for i in range(len(board_cards)):
        if not board_cards[i] or board_cards[i] == '??': continue
        eq = mc_redraw_board(hole_cards, board_cards, i, n)
        if eq > best[0]: best = (eq, 'board', i)
    return best


# ---------------------------------------------------------------------------
# Bet sizing — tuned for 250-chip stacks and 2/5 blinds
# ---------------------------------------------------------------------------

def choose_bet(equity, pot_odds, legal_actions, min_raise, max_raise,
               continue_cost, my_stack, rounds_played, opp_agg):
    """Return a betting action (no redraw wrapper)."""
    bluff_rate = 0.06 if rounds_played > 20 and opp_agg / (rounds_played + 1) < 0.25 else 0.02

    if RaiseAction in legal_actions:
        if equity >= 0.80:
            # Very strong: push big (up to all-in)
            size = max_raise
            return RaiseAction(size)
        if equity >= RAISE_STRONG:
            # Strong: raise ~2/3 pot (use min_raise as floor)
            size = min(max_raise, max(min_raise, int(min_raise * 1.5)))
            return RaiseAction(size)
        if equity >= RAISE_MODERATE:
            return RaiseAction(min_raise)
        if equity < BLUFF_MAX and random.random() < bluff_rate:
            return RaiseAction(min_raise)

    if equity >= CALL_MIN or equity >= pot_odds:
        if CallAction in legal_actions and continue_cost > 0:
            return CallAction()
        if CheckAction in legal_actions:
            return CheckAction()

    if CheckAction in legal_actions:
        return CheckAction()
    if FoldAction in legal_actions:
        return FoldAction()
    return CallAction()


# ---------------------------------------------------------------------------
# Player
# ---------------------------------------------------------------------------

class Player(Bot):

    def __init__(self):
        self.opp_agg      = 0
        self.rounds_played = 0

    def handle_new_round(self, game_state, round_state, active):
        pass

    def handle_round_over(self, game_state, terminal_state, active):
        prev = terminal_state.previous_state
        # Track opponent aggression (bet > 2x BB = aggressive)
        if prev.pips[1 - active] > BIG_BLIND * 2:
            self.opp_agg += 1
        self.rounds_played += 1

    def get_action(self, game_state, round_state, active):
        legal_actions = round_state.legal_actions()
        street        = round_state.street
        my_cards      = round_state.hands[active]
        board_cards   = list(round_state.board)
        my_pip        = round_state.pips[active]
        opp_pip       = round_state.pips[1 - active]
        continue_cost = opp_pip - my_pip
        pot_total     = sum(round_state.pips) + continue_cost
        my_stack      = round_state.stacks[active]

        min_raise = max_raise = None
        if RaiseAction in legal_actions:
            min_raise, max_raise = round_state.raise_bounds()

        pot_odds   = continue_cost / (pot_total + 1e-9)
        can_redraw = RedrawAction in legal_actions

        # -------------------------------------------------------------------
        # Preflop (street == 0)
        # -------------------------------------------------------------------
        if street == 0:
            valid = [c for c in my_cards if c and c != '??']
            if len(valid) < 2:
                return CheckAction() if CheckAction in legal_actions else FoldAction()

            key   = hand_to_key(valid)
            entry = LOOKUP.get(key)

            if entry:
                equity     = entry['equity']
                best_r_eq  = entry['best_redraw']
                gain       = entry['redraw_gain']
                best_r_idx = entry['best_redraw_card']
            else:
                equity     = mc_equity(valid, [], n=400)
                r0         = mc_redraw_hole(valid, [], 0, n=150)
                r1         = mc_redraw_hole(valid, [], 1, n=150)
                best_r_eq  = max(r0, r1)
                gain       = best_r_eq - equity
                best_r_idx = 0 if r0 >= r1 else 1

            # With 50x stack, fold weak hands facing a raise
            if continue_cost > BIG_BLIND and equity < PREFLOP_FOLD_EQ:
                if FoldAction in legal_actions:
                    return FoldAction()

            # Redraw preflop: we have edge since opponent cannot redraw
            if can_redraw and equity < PREFLOP_REDRAW_EQ_MAX and gain >= PREFLOP_REDRAW_MIN_GAIN:
                bet = choose_bet(best_r_eq, pot_odds, legal_actions,
                                 min_raise, max_raise, continue_cost,
                                 my_stack, self.rounds_played, self.opp_agg)
                return RedrawAction('hole', best_r_idx, bet)

            return choose_bet(equity, pot_odds, legal_actions,
                              min_raise, max_raise, continue_cost,
                              my_stack, self.rounds_played, self.opp_agg)

        # -------------------------------------------------------------------
        # Flop / Turn / River
        # -------------------------------------------------------------------
        iters  = {3: 180, 4: 250, 5: 320}.get(street, 180)
        equity = mc_equity(my_cards, board_cards, n=iters)

        # Stack-to-pot ratio check: with shallow stacks, commit more readily
        spr = my_stack / (pot_total + 1e-9)

        if can_redraw and equity < POST_REDRAW_EQ_MAX:
            best_r_eq, ttype, tidx = best_redraw(
                my_cards, board_cards, n=iters // 3
            )
            if best_r_eq - equity >= POST_REDRAW_MIN_GAIN:
                bet = choose_bet(best_r_eq, pot_odds, legal_actions,
                                 min_raise, max_raise, continue_cost,
                                 my_stack, self.rounds_played, self.opp_agg)
                return RedrawAction(ttype, tidx, bet)

        # With low SPR (< 3), lean toward committing with decent equity
        if spr < 3 and equity >= 0.50 and RaiseAction in legal_actions:
            return RaiseAction(max_raise)

        return choose_bet(equity, pot_odds, legal_actions,
                          min_raise, max_raise, continue_cost,
                          my_stack, self.rounds_played, self.opp_agg)


if __name__ == '__main__':
    run_bot(Player(), parse_args())
